# The example Pod utilizing the profile loaded by the sample daemon.

apiVersion: v1
kind: Pod
metadata:
  name: orderCapture
  # To capture order
  labels:
    app: orderCapture
  annotations:
    # Tell Kubernetes to apply the AppArmor profile "k8s-nginx".
    # Note that this is ignored if the Kubernetes node is not running version 1.4 or greater.
    #container.apparmor.security.beta.kubernetes.io/nginx: localhost/k8s-nginx
spec:
  containers:
  - name: orderCapture
    image: shanepeckham/captureorderack
    ports:
    - containerPort: 80