apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderfulfill
  labels:
    app: orderfulfill
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderfulfill
  template:
    metadata:
      labels:
        app: orderfulfill
    spec:
      containers:
      - name: orderfulfill
        image: shanepeckham/fulfillorderack:v6
        ports:
        - containerPort: 8080
        env:
          - name: TEAMNAME
            value: "Team9"
          - name: MONGOHOST
            value: "mongodb://mongo-mongodb.default"  
        volumeMounts:
        - name: azurefile
          mountPath: /orders
      volumes:
      - name: azurefile
        persistentVolumeClaim: 
          claimName: azurefile  
---
kind: Service
apiVersion: v1
metadata:
  name: orderfulfill
  labels:
    app: orderfulfill
spec:
  selector:
    app: orderfulfill
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: azurefile
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
  

