apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordercapture
  labels:
    app: ordercapture
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordercapture
  template:
    metadata:
      labels:
        app: ordercapture
    spec:
      containers:
      - name: ordercapture
        image: shanepeckham/captureorderack:v6
        ports:
        - containerPort: 8080
        env:
          - name: TEAMNAME
            value: "Team9"
          - name: MONGOHOST
            value: "mongodb://mongo-mongodb.default"
---
kind: Service
apiVersion: v1
metadata:
  name: ordercapture
  labels:
    app: ordercapture
spec:
  selector:
    app: ordercapture
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer